<script lang="ts">
 import {onMount} from 'svelte';
 import Icon from './components/Icon.svelte';import DrawingPad from './components/DrawingPad.svelte';import FieldGroup from './components/FieldGroup.svelte';import Record from './components/Record.svelte';import Help from './components/Help.svelte';
 import {groupsI,groupsII,stages,intro,demoTargets,duration,newSession,type Session,type Stroke} from './data';
 import {bootstrapFromHash,getReady,getCatalogSummary,shutdown,type Readiness,type CatalogSummary} from './api';
 type Page='home'|'session'|'history'|'stats'|'settings'|'closed';
 let page:Page='home';let sessions:Session[]=[];let currentId='';let dark=false;let helpOpen=false;let tour=false;let helpStep=0;let paused=false;let storeMessage='Salvo neste navegador';let mode='Familiarização';let historyFilter='Todas';let lightbox:number|null=null;let disposition='';let concentration='';let recordOpen=false;
 let blockDialog=false;let confirmChoice=false;let notice='';let loaded=false;
 let appConnected=false;let appShell=false;let readiness:Readiness|null=null;let catalogSummary:CatalogSummary|null=null;let bootError='';let shuttingDown=false;
 $: phase1Locked=appShell;
 $: current=sessions.find(s=>s.id===currentId);
 $: active=sessions.find(s=>s.status==='active'||s.status==='locked');
 $: step=current?.step??0;
 $: done=sessions.filter(s=>s.status==='done');
 $: hits=done.filter(s=>s.selected===s.target).length;
 $: shown=sessions.filter(s=>historyFilter==='Todas'||(historyFilter==='Concluídas'?s.status==='done':s.status==='abandoned'));
 const KEY='crv-design-prototype-v1';
 function save(){if(phase1Locked){storeMessage='Preferência local';try{localStorage.setItem(KEY,JSON.stringify({dark}));}catch{}return true;}try{localStorage.setItem(KEY,JSON.stringify({sessions,currentId,dark}));storeMessage='Salvo neste navegador';return true;}catch{storeMessage='Falha ao salvar — mantenha esta aba aberta';return false;}}
 function touch(){sessions=[...sessions];save();}
 function start(){if(phase1Locked){notice='Sessões reais abrem na Fase 2.';return;}if(active){currentId=active.id;page='session';return;}const s=newSession(mode);s.notes.disposition=disposition;s.notes.concentration=concentration;sessions=[s,...sessions];currentId=s.id;paused=false;if(save())page='session';else{sessions=sessions.filter(x=>x.id!==s.id);currentId='';}}
 function editGroup(key:string,v:string[],n:string){if(!current||current.status!=='active')return;current.record[key]=v;current.notes[key]=n;touch();}
 function note(key:string,val:string){if(!current||current.status!=='active')return;current.notes[key]=val;touch();}
 function draw(key:string,v:Stroke[]){if(!current||current.status!=='active')return;current.drawings[key]=v;touch();}
 function go(n:number){if(!current)return;if(current.status==='active'&&n>=1&&n<=4){current.step=n;touch();window.scrollTo(0,0);}}
 function lock(){if(!current)return;const old=current.step;current.status='locked';current.step=5;if(save()){blockDialog=false;touch();window.scrollTo(0,0);}else{current.status='active';current.step=old;touch();}}
 function choose(){if(!current||current.selected===null)return;current.status='done';current.step=6;if(save()){confirmChoice=false;touch();window.scrollTo(0,0);}else{current.status='locked';current.step=5;touch();}}
 function select(id:number){if(!current||current.status!=='locked')return;current.selected=id;touch();}
 function abandon(){if(!current||!confirm('Abandonar esta demonstração? O registro ficará no histórico.'))return;current.status='abandoned';touch();page='history';}
 function prepare(){if(phase1Locked){notice='Nova sessão estará disponível na Fase 2, após o cegamento e a persistência no servidor.';page='home';return;}if(active){currentId=active.id;page='session';}else{currentId='';page='session';}paused=false;}
 function openHistory(s:Session){if(phase1Locked)return;currentId=s.id;page='session';paused=false;}
 async function end(){if(phase1Locked){if(!appConnected){notice='Reinicie pelo executável para obter um token e poder encerrar o servidor.';return;}shuttingDown=true;const ok=await shutdown();if(ok){page='closed';paused=true;}else{shuttingDown=false;notice='Falha ao encerrar o servidor. Tente de novo.';}return;}if(save()){page='closed';paused=true;}}
 function toggleTheme(){dark=!dark;save();}
 function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function csv(){download('crv-demonstracoes.csv','codigo;data;estado;acerto;tempo_coleta\n'+sessions.map(s=>`${s.code};${s.created};${s.status};${s.status==='done'?(s.selected===s.target?1:0):''};${s.seconds}`).join('\n'),'text/csv;charset=utf-8');}
 function backup(){download('crv-prototipo-backup.json',JSON.stringify({version:1,sessions},null,2));}
 async function restore(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.version!==1||!Array.isArray(d.sessions)||d.sessions.some((s:Session)=>!s.id||!s.drawings||!s.notes||!s.record||!Array.isArray(s.summary)||!Array.isArray(s.order)||!Number.isInteger(s.target)||s.target<0||s.target>3||!['active','locked','done','abandoned'].includes(s.status)))throw Error();if(!confirm('Substituir o histórico demonstrativo deste navegador pelo arquivo?'))return;sessions=d.sessions;currentId='';save();notice='Histórico demonstrativo restaurado.';}catch{notice='Arquivo inválido. O histórico atual foi preservado.';}(e.target as HTMLInputElement).value='';}
 onMount(()=>{(async()=>{try{const raw=localStorage.getItem(KEY);if(raw){const d=JSON.parse(raw);dark=!!d.dark;if(!location.hash.includes('bootstrap=')){sessions=d.sessions??[];currentId=d.currentId??'';}}}catch{storeMessage='Armazenamento indisponível';}
 const localApp=location.protocol.startsWith('http')&&(location.hostname==='127.0.0.1'||location.hostname==='localhost'||location.hostname==='[::1]');
 try{const ok=await bootstrapFromHash();if(ok){appShell=true;appConnected=true;sessions=[];currentId='';readiness=await getReady();catalogSummary=await getCatalogSummary();storeMessage='Servidor local conectado';}else if(localApp){appShell=true;sessions=[];currentId='';bootError='Abra o aplicativo pelo executável Go (URL com token) para autenticar esta aba.';}}catch{if(localApp){appShell=true;sessions=[];currentId='';}bootError='Servidor local indisponível.';}
 loaded=true;})();
 const timer=setInterval(()=>{if(phase1Locked)return;if(page==='session'&&current&&!paused&&document.visibilityState==='visible'){if(current.status==='active')current.seconds++;if(current.status==='locked')current.choiceSeconds++;touch();}},1000);return()=>clearInterval(timer);});
</script>
<svelte:window onkeydown={(e)=>{if(e.key==='Escape'){lightbox=null;blockDialog=false;confirmChoice=false;}}}/>
<div class="app" class:dark>
<header class="app-header"><button class="brand" onclick={()=>{page='home';paused=true;}} aria-label="CRV — início">CRV<span class="brand-dot"></span></button><span class="header-divider"></span><span class="demo-label">{phase1Locked?'Fase 1 · em construção':'Protótipo de interface'}</span><div class="header-right">{#if page==='session'&&current&&!phase1Locked}<span class="code">{current.code}</span><span class="timer"><Icon name="clock" size={15}/>{duration(current.status==='locked'?current.choiceSeconds:current.seconds)}</span>{#if current.status==='active'||current.status==='locked'}<button class="icon-button" onclick={()=>paused=!paused} aria-label={paused?'Retomar cronômetro':'Pausar cronômetro'}><Icon name={paused?'play':'pause'}/></button>{/if}{/if}<button class="icon-button theme-toggle" onclick={toggleTheme} aria-label="Alternar tema"><Icon name={dark?'sun':'moon'}/></button><button class="exit-button" aria-label="Salvar e encerrar" onclick={end} disabled={shuttingDown}><Icon name="exit" size={16}/><span>{shuttingDown?'Encerrando…':'Salvar e encerrar'}</span></button></div></header>
{#if page==='closed'}
 <main class="closed-screen"><Icon name="check" size={38}/><h1>{phase1Locked?'Aplicativo encerrado.':'Demonstração salva.'}</h1><p>{phase1Locked?'O servidor local foi solicitado a fechar. Você pode fechar esta aba.':'Você pode fechar esta aba. Seu registro ficará neste navegador.'}</p>{#if !phase1Locked}<p class="muted">No aplicativo final, este botão também encerrará o servidor local.</p><button class="primary" onclick={()=>{page='home';paused=false;}}>Voltar ao protótipo <Icon name="arrow"/></button>{/if}</main>
{:else if page==='session'}
 <nav class="stepper" aria-label="Etapas da sessão">{#each stages as stage,i}<button class:active={step===i} class:complete={i<step} disabled={!(current?.status==='active'&&i>=1&&i<=step&&i<=4)} onclick={()=>go(i)}><span class="step-dot">{#if i<step}<Icon name="check" size={11}/>{/if}</span><span>{stage}</span></button>{/each}</nav>
 <main class="session-main">
 <div class="page-title"><div><h1>{stages[step]}</h1><p>{intro[step]}</p></div><button class="secondary" onclick={()=>{helpStep=step;tour=false;helpOpen=true;}}><Icon name="help"/>Como preencher</button></div>
 {#if paused&&current&&current.status!=='done'}<div class="inline-note">Cronômetro pausado. <button class="text-button" onclick={()=>paused=false}>Retomar</button></div>{/if}
 {#if !current}
 <div class="prepare-layout"><section class="surface prep-main"><h2>Uma sessão, três etapas.</h2><p class="lead">Desenhe, descreva e só depois compare.</p><div class="prep-stages">{#each ['Ideograma','Sensorial','Esboço'] as text,i}<div><span>0{i+1}</span><h3>{text}</h3><p>{['Um gesto e suas primeiras impressões.','Qualidades simples, sem identificar o objeto.','Formas e relações no espaço.'][i]}</p></div>{/each}</div><div class="prep-form"><label>Disposição <span class="muted">opcional</span><input bind:value={disposition} placeholder="Como você está se sentindo?"/></label><label>Concentração <span class="muted">opcional</span><select bind:value={concentration}><option value="">Não informar</option><option>Baixa</option><option>Moderada</option><option>Alta</option></select></label></div></section><aside class="surface prep-aside"><h3>Antes de começar</h3><p>Reserve cerca de 10 minutos. Não há limite obrigatório de tempo.</p><hr/><label>Modalidade<select bind:value={mode}><option>Familiarização</option><option disabled>Avaliação — na versão com Go</option></select></label><div class="help-note"><strong>Demonstração visual</strong><p>Quatro fotografias de exemplo serão reutilizadas. Seu banco SRV não foi importado. Este protótipo não serve para avaliar acurácia.</p></div></aside></div>
 {:else if current.status==='abandoned'}
 <section class="surface"><h2>Sessão abandonada</h2><p>O registro foi preservado. O alvo continua oculto.</p><Record session={current}/></section>
 {:else if step===1}
 <div class="work-grid"><div class="drawing-column"><DrawingPad strokes={current.drawings.ideogram} onchange={(v)=>draw('ideogram',v)}/><div class="inline-guidance"><Icon name="pen" size={17}/><span>Primeiro o gesto. A interpretação pode ficar em branco.</span></div></div><section class="surface inspector">{#if !current.attributes}<div class="attribute-intro"><h2>Deixe o gesto vir primeiro.</h2><p>Quando quiser, abra os atributos para registrar movimento, sensação e categoria geral.</p><button class="primary" onclick={()=>{if(current){current.attributes=true;touch();}}}>Registrar impressões <Icon name="arrow"/></button><p class="small muted">Você também pode continuar sem preencher.</p></div>{:else}{#each groupsI as group}<FieldGroup {group} values={current.record[group.key]||[]} note={current.notes[group.key]||''} onchange={(v,n)=>editGroup(group.key,v,n)}/>{/each}<label class="notes-label">Hipóteses / AOL<textarea rows="3" value={current.notes.aol1||''} oninput={(e)=>note('aol1',e.currentTarget.value)} placeholder="Identificações e interpretações que surgirem."></textarea></label>{/if}</section></div>
 {:else if step===2}
 <div class="sensory-grid">{#each groupsII as group}<section class="surface"><FieldGroup {group} values={current.record[group.key]||[]} note={current.notes[group.key]||''} onchange={(v,n)=>editGroup(group.key,v,n)}/></section>{/each}</div><div class="two-notes"><label>Outras impressões sensoriais<textarea rows="3" value={current.notes.sensory||''} oninput={(e)=>note('sensory',e.currentTarget.value)} placeholder="Algo que não apareceu nas opções?"></textarea></label><label>Hipóteses / AOL<textarea rows="3" value={current.notes.aol2||''} oninput={(e)=>note('aol2',e.currentTarget.value)} placeholder="Registre suas interpretações separadamente."></textarea></label></div>
 {:else if step===3}
 <div class="work-grid sketch-grid"><div class="drawing-column"><DrawingPad strokes={current.drawings.sketch} onchange={(v)=>draw('sketch',v)}/><div class="inline-guidance"><Icon name="pen" size={17}/><span>Linhas simples são suficientes. Não é um teste de desenho.</span></div></div><section class="surface inspector">{#each [['forms','Formas'],['dimensions','Dimensões / proporções'],['positions','Posições e relações espaciais'],['spatial','Outras anotações'],['aol3','Hipóteses / AOL']] as [key,title]}<label class="notes-label">{title}<textarea rows="2" value={current.notes[key]||''} oninput={(e)=>note(key,e.currentTarget.value)} placeholder="Escreva livremente, se quiser."></textarea></label>{/each}</section></div>
 {:else if step===4}
 <div class="review-layout"><section class="surface review-record"><h2>Seu registro</h2><Record session={current}/></section><aside class="surface sticky-panel"><h2>O que mais se destacou?</h2><p class="muted">Até cinco características. Todas opcionais.</p>{#each current.summary as val,i}<label class="summary-input"><span>{i+1}</span><input aria-label={`Característica ${i+1}`} value={val} oninput={(e)=>{if(current){current.summary[i]=e.currentTarget.value;touch();}}} placeholder="Uma característica principal"/></label>{/each}<label class="notes-label">Confiança no registro (%)<input type="number" min="0" max="100" value={current.confidence} oninput={(e)=>{if(current){current.confidence=e.currentTarget.value===''?'':String(Math.max(0,Math.min(100,Number(e.currentTarget.value))));touch();}}} placeholder="Opcional"/></label><div class="help-note"><Icon name="lock"/><p>Ao finalizar, o registro será bloqueado. Você verá as quatro alternativas em seguida.</p></div></aside></div>
 {:else if step===5}
 <div class="choice-layout"><aside class="surface choice-record"><h2>Seu registro <Icon name="lock" size={16}/></h2><p class="muted small">Somente leitura</p><Record session={current} compact/></aside><section><div class="target-grid">{#each current.order as id,i}<div class="target-card" class:selected={current.selected===id}><button class="target-select" onclick={()=>select(id)} aria-label={`Selecionar alternativa ${'ABCD'[i]}`} aria-pressed={current.selected===id}><img src={demoTargets[id].image} alt={`Alternativa ${'ABCD'[i]}`}/><span class="target-label"><b>{'ABCD'[i]}</b><span>{current.selected===id?'Selecionada':'Selecionar imagem'}</span>{#if current.selected===id}<Icon name="check"/>{/if}</span></button><button class="expand" aria-label={`Ampliar alternativa ${'ABCD'[i]}`} onclick={()=>lightbox=id}><Icon name="expand" size={16}/></button></div>{/each}</div><div class="choice-bottom"><p class="muted">Considere o conjunto, inclusive as divergências.</p><label>Confiança na escolha (%)<input type="number" min="0" max="100" value={current.choiceConfidence} placeholder="Opcional" oninput={(e)=>{if(current){current.choiceConfidence=e.currentTarget.value===''?'':String(Math.max(0,Math.min(100,Number(e.currentTarget.value))));touch();}}}/></label></div></section></div>
 {:else if step===6}
 <div class="feedback-layout"><section class="surface feedback-photo"><div class="result-line"><span class="result-icon"><Icon name={current.selected===current.target?'check':'arrow'} size={24}/></span><div><h2>{current.selected===current.target?'Você escolheu o alvo sorteado.':'O alvo sorteado era outra imagem.'}</h2><p class="muted">Sua escolha: {'ABCD'[current.order.indexOf(current.selected!)]} · Alvo correto: {'ABCD'[current.order.indexOf(current.target)]}</p></div></div><button class="feedback-image" onclick={()=>lightbox=current!.target} aria-label="Ampliar alvo correto"><img src={demoTargets[current.target].image} alt={demoTargets[current.target].name}/></button><h2>{demoTargets[current.target].name}</h2><p>{demoTargets[current.target].description}</p><details><summary>Detalhes do alvo</summary><p class="small">Fonte: {demoTargets[current.target].credit}</p><p class="small">Atributos SAM indisponíveis nesta demonstração. No app final, virão do seu banco.</p></details></section><aside class="surface sticky-panel"><h2>Depois do feedback</h2><p class="muted">O que correspondeu? O que divergiu?</p><label>Comentário posterior<textarea rows="7" value={current.comment} oninput={(e)=>{if(current){current.comment=e.currentTarget.value;touch();}}} placeholder="Esta reflexão fica separada do registro original."></textarea></label><div class="timings"><div><span>Coleta</span><strong>{duration(current.seconds)}</strong></div><div><span>Escolha</span><strong>{duration(current.choiceSeconds)}</strong></div></div><button class="secondary w-full" onclick={()=>recordOpen=!recordOpen}>{recordOpen?'Ocultar':'Consultar'} registro original <Icon name="chevron"/></button><p class="small muted">Resultado demonstrativo, sem valor experimental.</p></aside></div>{#if recordOpen}<section class="surface mt"><Record session={current}/></section>{/if}
 {/if}
 </main>
 <footer class="session-footer"><div>{#if current&&current.status==='active'}<button class="secondary" onclick={()=>step===1?(page='home',paused=true):go(step-1)}><Icon name="back"/>Voltar</button><button class="text-button abandon" onclick={abandon}>Abandonar</button>{:else}<button class="secondary" onclick={()=>page='home'}><Icon name="back"/>Início</button>{#if current?.status==='locked'}<button class="text-button abandon" onclick={abandon}>Abandonar</button>{/if}{/if}</div><span class="footer-hint">{current?storeMessage:'Todas as respostas são opcionais'}</span>{#if !current}<button class="primary" onclick={start}>Iniciar demonstração <Icon name="arrow"/></button>{:else if current.status==='abandoned'}<button class="primary" onclick={()=>page='history'}>Ver histórico <Icon name="arrow"/></button>{:else if step<4}<button class="primary" onclick={()=>go(step+1)}>Continuar <Icon name="arrow"/></button>{:else if step===4}<button class="primary" onclick={()=>blockDialog=true}>Finalizar registro <Icon name="lock" size={16}/></button>{:else if step===5}<button class="primary" disabled={current.selected===null} onclick={()=>confirmChoice=true}>Confirmar escolha <Icon name="arrow"/></button>{:else}<button class="primary" onclick={()=>page='history'}>Concluir e ver histórico <Icon name="arrow"/></button>{/if}</footer>
{:else}
 <div class="shell"><nav class="sidebar" aria-label="Navegação principal">{#each [['home','Início','home'],['history','Histórico','clock'],['stats','Estatísticas','chart'],['settings','Configurações','settings']] as [id,label,icon]}<button class:nav-active={page===id} onclick={()=>{page=id as Page;paused=true;}}><Icon name={icon}/>{label}</button>{/each}<div class="sidebar-bottom"><button onclick={()=>{helpStep=0;tour=true;helpOpen=true;}}><Icon name="book"/>Conhecer o fluxo</button><p>CRV · Estágios I–III<br/>{phase1Locked?'Fase 1 · offline local':'Demonstração local'}</p></div></nav>
 <main class="dashboard">
 {#if page==='home'}
 <div class="page-title"><div><h1>Seu espaço de prática.</h1><p>Um registro por vez, da primeira impressão ao feedback.</p></div></div>
 {#if appConnected}
 <section class="inline-note readiness-banner" role="status">
  {#if readiness?.ready}<strong>Catálogo pronto.</strong> {readiness.eligibleCount} imagens elegíveis · {readiness.excludedCount} exclusões. Sessões reais abrem na Fase 2.
  {:else}<strong>Catálogo indisponível.</strong> {readiness?.message || bootError || 'Aguardando inicialização.'}{/if}
 </section>
 {/if}
 {#if bootError && !appConnected}<section class="inline-note" role="status">{bootError}</section>{/if}
 {#if notice}<section class="inline-note" role="status">{notice}</section>{/if}
 <section class="home-start"><div><h2>{phase1Locked?'Aplicativo local em construção.':(active?'Seu registro espera por você.':'Comece com uma folha em branco.')}</h2><p>{phase1Locked?'O banco incluído foi validado nesta instalação. A coleta cega e a escolha entre quatro imagens chegam na Fase 2.':(active?'Retome a mesma sessão, com os desenhos e anotações preservados.':'Explore os três estágios com calma. As imagens só aparecem depois de finalizar seu registro.')}</p><button class="primary" onclick={prepare} disabled={phase1Locked} title={phase1Locked?'Disponível na Fase 2':''}>{phase1Locked?'Nova sessão (Fase 2)':(active?'Continuar sessão':'Nova sessão')}<Icon name="arrow"/></button></div><div class="home-flow">{#each ['Ideograma','Sensorial','Esboço'] as v,i}<div><span>0{i+1}</span><div><h3>{v}</h3><p>{['Registre o gesto.','Descreva as qualidades.','Explore as formas.'][i]}</p></div></div>{/each}</div></section>
 <section class="home-bottom"><div><h2>Antes de experimentar</h2><p class="muted">Uma explicação curta em cada etapa. Exemplos disponíveis quando você precisar.</p><button class="secondary" onclick={()=>{tour=true;helpStep=0;helpOpen=true;}}><Icon name="book"/>Conhecer o fluxo</button></div><div class="demo-note"><h3>{phase1Locked?'Fase 1 · inicialização offline':'Este é um protótipo navegável'}</h3><p>{phase1Locked?'Tema, ajuda e prontidão do catálogo estão ativos. Histórico, estatísticas e sessões reais ainda não estão ligados ao servidor.':'Desenhos e registros ficam neste navegador. O banco SRV, o backend Go e os blocos de avaliação serão integrados na próxima etapa.'}</p>{#if !phase1Locked}<p class="small">As quatro imagens de exemplo se repetem; os resultados são apenas demonstrativos.</p>{/if}</div></section>
 {#if !phase1Locked && sessions.length}<section class="recent"><div class="section-heading"><h2>Sessões recentes</h2><button class="text-button" onclick={()=>page='history'}>Ver histórico <Icon name="arrow" size={16}/></button></div>{#each sessions.slice(0,3) as s}<button class="history-row" onclick={()=>openHistory(s)}><span class="code">{s.code}</span><span>{new Date(s.created).toLocaleDateString('pt-BR')}</span><span>{s.status==='done'?'Concluída':s.status==='abandoned'?'Abandonada':'Em andamento'}</span><Icon name="arrow"/></button>{/each}</section>{/if}
 {:else if page==='history'}
 <div class="page-title"><div><h1>Histórico</h1><p>{phase1Locked?'Histórico real chega na Fase 3.':'Seus registros demonstrativos, preservados por sessão.'}</p></div>{#if !phase1Locked}<button class="secondary" onclick={csv} disabled={!sessions.length}><Icon name="download"/>Exportar CSV</button>{/if}</div>
 {#if phase1Locked}<section class="empty-state"><Icon name="book" size={40}/><h2>Ainda sem sessões reais.</h2><p>A Fase 1 só valida o catálogo e o servidor local. Coleta e histórico vêm nas fases seguintes.</p></section>
 {:else}<div class="section-heading"><label class="filter-label">Mostrar<select bind:value={historyFilter}><option>Todas</option><option>Concluídas</option><option>Abandonadas</option></select></label><span class="muted small">{shown.length} registros</span></div>
 {#if !shown.length}<section class="empty-state"><Icon name="book" size={40}/><h2>Nenhum registro por aqui.</h2><p>Suas sessões aparecerão aqui quando você começar.</p><button class="primary" onclick={prepare}>Nova sessão <Icon name="arrow"/></button></section>{:else}<div class="table-wrap"><table><thead><tr><th>Sessão</th><th>Data</th><th>Estado</th><th>Coleta</th><th>Resultado</th><th></th></tr></thead><tbody>{#each shown as s}<tr><td class="code">{s.code}</td><td>{new Date(s.created).toLocaleDateString('pt-BR')}</td><td>{s.status==='done'?'Concluída':s.status==='abandoned'?'Abandonada':'Em andamento'}</td><td>{duration(s.seconds)}</td><td>{s.status==='done'?(s.selected===s.target?'Acerto':'Erro'):'—'}</td><td><button class="text-button" onclick={()=>openHistory(s)}>Abrir <Icon name="arrow" size={15}/></button></td></tr>{/each}</tbody></table></div>{/if}{/if}
 {:else if page==='stats'}
 <div class="page-title"><div><h1>Estatísticas</h1><p>{phase1Locked?'Estatísticas contínuas chegam na Fase 3.':'Um resumo das demonstrações realizadas neste navegador.'}</p></div></div>
 {#if phase1Locked}<section class="empty-state"><Icon name="chart" size={40}/><h2>Sem dados de sessão ainda.</h2><p>A Fase 1 não conta acertos. O gráfico cumulativo virá com o histórico real.</p></section>
 {:else}<div class="stat-strip"><div><span>Iniciadas</span><strong>{sessions.length}</strong></div><div><span>Concluídas</span><strong>{done.length}</strong></div><div><span>Acertos</span><strong>{hits}<small> / {done.length}</small></strong></div><div><span>Taxa de acertos</span><strong>{done.length?Math.round(hits/done.length*100)+'%':'—'}</strong></div></div>
 <section class="surface stats-panel"><h2>Acertos e referência de acaso</h2><div class="bar-row"><span>Demonstração</span><div class="bar-track"><div style={`width:${done.length?hits/done.length*100:0}%`}></div></div><strong>{done.length?Math.round(hits/done.length*100)+'%':'—'}</strong></div><div class="bar-row"><span>Acaso</span><div class="bar-track"><div class="chance" style="width:25%"></div></div><strong>25%</strong></div><p class="muted">{sessions.filter(s=>s.status==='abandoned').length} sessões abandonadas · {sessions.filter(s=>s.status==='active'||s.status==='locked').length} em andamento</p></section><div class="demo-note mt"><h3>Sem interpretação experimental</h3><p>As imagens se repetem e o alvo fica nos dados do navegador. Blocos fixos, controle de exposição, intervalo de confiança e teste binomial pertencem à versão final com backend.</p></div>{/if}
 {:else if page==='settings'}
 <div class="page-title"><div><h1>Configurações</h1><p>{phase1Locked?'Preferências locais e resumo do catálogo instalado.':'Preferências da interface e dados desta demonstração.'}</p></div></div><section class="settings-section"><div><h2>Aparência</h2><p>O papel de desenho permanece branco nos dois temas.</p></div><button class="secondary" onclick={toggleTheme}><Icon name={dark?'sun':'moon'}/>{dark?'Usar tema claro':'Usar tema escuro'}</button></section><section class="settings-section"><div><h2>Banco de alvos</h2>{#if appConnected && catalogSummary}<p>Revisão ativa · {catalogSummary.catalogLabel || 'bundled'}</p><p class="small muted">{catalogSummary.eligibleCount} elegíveis · {catalogSummary.excludedCount} exclusões · sessões na Fase 2</p>{#if catalogSummary.exclusions?.length}<details class="catalog-exclusions"><summary>Ver exclusões (amostra)</summary><ul>{#each catalogSummary.exclusions as ex}<li class="small muted">{ex.reason}{#if ex.path} · {ex.path}{/if}</li>{/each}</ul></details>{/if}{:else}<p>{phase1Locked?'Autentique esta aba pela URL do executável para ver o resumo do catálogo.':'Pacote SRV · importação prevista para a versão com Go.'}</p><p class="small muted">{phase1Locked?'Sem pré-visualização de imagens nesta fase.':'Nesta versão: quatro fotografias demonstrativas locais.'}</p>{/if}</div><span class="muted small">{appConnected?(catalogSummary?.ready?'Pronto':'Indisponível'):(phase1Locked?'Aguardando autenticação':'Integração pendente')}</span></section>{#if !phase1Locked}<section class="settings-section"><div><h2>Dados do protótipo</h2><p>Salvar ou restaurar o histórico demonstrativo deste navegador.</p><p class="small muted">O arquivo JSON contém os dados internos dos alvos.</p></div><div class="settings-actions"><button class="secondary" onclick={backup}><Icon name="download"/>Exportar JSON</button><label class="file-button">Restaurar JSON<input type="file" accept=".json" onchange={restore}/></label></div></section>{/if}{#if notice}<p class="inline-note" role="status">{notice}</p>{/if}<section class="settings-section"><div><h2>Aplicativo local</h2><p>Go + Chi · Svelte · SQLite · Tailwind<br/>Windows e Linux, offline, com históricos independentes.</p></div></section>
 {/if}
 <p class="dashboard-foot">Sem nuvem. Sem interpretação automática. Um registro de cada vez.</p>
 </main></div>
{/if}
{#if helpOpen}<Help step={helpStep} {tour} onclose={()=>helpOpen=false} onexample={()=>{if(current){current.openedExamples=[...current.openedExamples,helpStep];touch();}}}/>{/if}
{#if blockDialog||confirmChoice}<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><Icon name={blockDialog?'lock':'check'} size={28}/><h2 id="confirm-title">{blockDialog?'Finalizar seu registro?':'Confirmar esta escolha?'}</h2><p>{blockDialog?'As quatro imagens serão apresentadas. Seus desenhos e anotações não poderão mais ser alterados.':'Sua escolha será definitiva. O alvo correto será revelado em seguida.'}</p><div class="modal-actions"><button class="secondary" onclick={()=>{blockDialog=false;confirmChoice=false;}}>Voltar</button><button class="primary" onclick={blockDialog?lock:choose}>{blockDialog?'Bloquear e ver imagens':'Confirmar e revelar'}</button></div></div></div>{/if}
{#if lightbox!==null}<div class="lightbox" role="dialog" aria-modal="true" aria-label="Imagem ampliada"><button class="lightbox-close" onclick={()=>lightbox=null} aria-label="Fechar imagem"><Icon name="close" size={25}/></button><img src={demoTargets[lightbox].image} alt="Imagem ampliada"/></div>{/if}
</div>
